[project]
name = "user-management-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "seachran", email = "motolko.leonid.1980@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
user-management-service = "user_management_service:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "alembic>=1.19.1",
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
    "ty>=0.0.68",
]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warning
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "B",   # flake8-bugbear (bugs serch)
    "UP",  # pyupgrade (update syntax)
    "SIM", # simplify code
    "FAST" # rules for FastAPI
]

[tool.ty.environment]
python-version = "3.13"

[tool.ty.src]
include = ["scr"]
